ProgettoFinale_GuidoCafarelli/Controllers/OrdiniMagazzinoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoFinale_GuidoCafarelli.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrdiniMagazzinoController : Controller
    {
        Model1 model = new Model1();
        public ActionResult Index(string cerca)
        {
            return View(model.OrdiniMagazzino.OrderBy(x => x.DataEntrata).Where(x => x.Prodotti.Nome.Contains(cerca) || cerca == null).ToList());
        }
        
    }
}

ProgettoFinale_GuidoCafarelli/Controllers/OrdiniNegoziController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoFinale_GuidoCafarelli.Controllers
{
    [Authorize(Roles = "Admin,PuntoVendita")]
    public class OrdiniNegoziController : Controller
    {
        Model1 model = new Model1();
        public ActionResult Index(string cerca)
        {
            return View(model.OrdiniNegozi.OrderByDescending(x => x.Data).Where(x => x.Users.User.Contains(cerca) || x.Prodotti.Nome.Contains(cerca) || cerca == null).ToList());
        }
    }
}

ProgettoFinale_GuidoCafarelli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    <script src="https://kit.fontawesome.com/e275ee0ca7.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="font-family: 'Montserrat'">
    <div class="container-fluid text-center" style="background-color: #ffd101">
        <img src="~/img/Logo.jpeg" style=" height:270px;width:600px;">
    </div>
    <nav class="navbar navbar-expand-lg py-3 hover:bg-sky-700" style="height: 90px; border-top: 5px solid #E6E6E6; border-bottom: 8px solid #E6E6E6; background-color: #1f3372; color: #E6E6E6 ">
        <div class="container-fluid mx-3">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
                <ul class="navbar-nav ">

                    <li class="nav-item liNav">
                     
                        @Html.ActionLink("Prodotti", "Index", "Prodotti", null, new { @class = "text-white mx-5", @style = "text-decoration:none; font-size:20px; font-weight:bold" })
                    </li>
                    <li class="nav-item liNav">
                     
                        @Html.ActionLink("Ordini Magazzino", "Index", "OrdiniMagazzino", null, new { @class = "text-white mx-5", @style = "text-decoration:none; font-size:20px; font-weight:bold" })
                    </li>
                    <li class="nav-item liNav">
                      
                        @Html.ActionLink("Ordini Negozi", "Index", "OrdiniNegozi", null, new { @class = "text-white mx-5", @style = "text-decoration:none; font-size:20px; font-weight:bold" })
                    </li>

                    <li class="nav-item liNav">
                    
                        @Html.ActionLink("Giacenze", "Giacenze", "Prodotti", null, new { @class = "text-white mx-5", @style = "text-decoration:none; font-size:20px; font-weight:bold" })
                    </li>

                    <li class="nav-item liNav">

                        @Html.ActionLink("Logout", "Logout", "Login", null, new { @class = "text-white mx-5", @style = "text-decoration:none; font-size:20px; font-weight:bold" })
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid body-content" style="min-height:100%">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <footer class="text-center" style="height: 90px; border-top: 5px solid #E6E6E6; border-bottom: 8px solid #E6E6E6; background-color: #1f3372; color: #E6E6E6; margin-top:200px;">
        <p>800 666 555. Servizio gratuito,lunedì-sabato, dalle 8.30 alle 20.00.</p>
        <p>assistenza.Esselunga@info.it</p>
    </footer>
</body>
</html>